//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.nabp.pmpi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisclosingPmpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisclosingPmpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InterconnectPmpId" type="{http://pmpi.nabp.org/}InterconnectPmpIdType"/>
 *         &lt;element name="PmpDisclosureId" type="{http://pmpi.nabp.org/}PmpDisclosureIdType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisclosingPmpType", propOrder = {
    "interconnectPmpId",
    "pmpDisclosureId"
})
public class DisclosingPmpType {

    @XmlElement(name = "InterconnectPmpId", required = true)
    protected BigInteger interconnectPmpId;
    @XmlElement(name = "PmpDisclosureId")
    protected String pmpDisclosureId;

    /**
     * Gets the value of the interconnectPmpId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInterconnectPmpId() {
        return interconnectPmpId;
    }

    /**
     * Sets the value of the interconnectPmpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInterconnectPmpId(BigInteger value) {
        this.interconnectPmpId = value;
    }

    /**
     * Gets the value of the pmpDisclosureId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmpDisclosureId() {
        return pmpDisclosureId;
    }

    /**
     * Sets the value of the pmpDisclosureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmpDisclosureId(String value) {
        this.pmpDisclosureId = value;
    }

}
