/*
   Copyright 2013 Collaborative For Universal Health (C4UH), Logicoy Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
  */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.nabp.pmpi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisclosingPmpOptionalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisclosingPmpOptionalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InterconnectPmpId" type="{http://pmpi.nabp.org/}InterconnectPmpIdType" minOccurs="0"/>
 *         &lt;element name="PmpDisclosureId" type="{http://pmpi.nabp.org/}PmpDisclosureIdType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisclosingPmpOptionalType", propOrder = {
    "interconnectPmpId",
    "pmpDisclosureId"
})
public class DisclosingPmpOptionalType {

    @XmlElement(name = "InterconnectPmpId")
    protected BigInteger interconnectPmpId;
    @XmlElement(name = "PmpDisclosureId")
    protected String pmpDisclosureId;

    /**
     * Gets the value of the interconnectPmpId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInterconnectPmpId() {
        return interconnectPmpId;
    }

    /**
     * Sets the value of the interconnectPmpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInterconnectPmpId(BigInteger value) {
        this.interconnectPmpId = value;
    }

    /**
     * Gets the value of the pmpDisclosureId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmpDisclosureId() {
        return pmpDisclosureId;
    }

    /**
     * Sets the value of the pmpDisclosureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmpDisclosureId(String value) {
        this.pmpDisclosureId = value;
    }

}
