//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.nabp.pmpi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisclosingPmpRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisclosingPmpRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InterconnectPmpId" type="{http://pmpi.nabp.org/}InterconnectPmpIdType" maxOccurs="unbounded"/>
 *         &lt;element name="RsaEncryptedAesKey" type="{http://pmpi.nabp.org/}RsaEncryptedAesKeyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisclosingPmpRequestType", propOrder = {
    "interconnectPmpId",
    "rsaEncryptedAesKey"
})
public class DisclosingPmpRequestType {

    @XmlElement(name = "InterconnectPmpId", required = true)
    protected List<BigInteger> interconnectPmpId;
    @XmlElement(name = "RsaEncryptedAesKey", required = true)
    protected String rsaEncryptedAesKey;

    /**
     * Gets the value of the interconnectPmpId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interconnectPmpId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterconnectPmpId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getInterconnectPmpId() {
        if (interconnectPmpId == null) {
            interconnectPmpId = new ArrayList<BigInteger>();
        }
        return this.interconnectPmpId;
    }

    /**
     * Gets the value of the rsaEncryptedAesKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsaEncryptedAesKey() {
        return rsaEncryptedAesKey;
    }

    /**
     * Sets the value of the rsaEncryptedAesKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsaEncryptedAesKey(String value) {
        this.rsaEncryptedAesKey = value;
    }

}
