//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.nabp.pmpi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EncryptedDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncryptedDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RsaEncryptedAesKey" type="{http://pmpi.nabp.org/}RsaEncryptedAesKeyType"/>
 *         &lt;element name="AesEncryptedData" type="{http://pmpi.nabp.org/}AesEncryptedDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncryptedDataType", propOrder = {
    "rsaEncryptedAesKey",
    "aesEncryptedData"
})
public class EncryptedDataType {

    @XmlElement(name = "RsaEncryptedAesKey", required = true)
    protected String rsaEncryptedAesKey;
    @XmlElement(name = "AesEncryptedData", required = true)
    protected String aesEncryptedData;

    /**
     * Gets the value of the rsaEncryptedAesKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsaEncryptedAesKey() {
        return rsaEncryptedAesKey;
    }

    /**
     * Sets the value of the rsaEncryptedAesKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsaEncryptedAesKey(String value) {
        this.rsaEncryptedAesKey = value;
    }

    /**
     * Gets the value of the aesEncryptedData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAesEncryptedData() {
        return aesEncryptedData;
    }

    /**
     * Sets the value of the aesEncryptedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAesEncryptedData(String value) {
        this.aesEncryptedData = value;
    }

}
