/*
   Copyright 2013 Collaborative For Universal Health (C4UH), Logicoy Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
  */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.nabp.pmpi;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.nabp.pmpi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PmpDisclosures_QNAME = new QName("http://pmpi.nabp.org/", "PmpDisclosures");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.nabp.pmpi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PmpDisclosureType }
     * 
     */
    public PmpDisclosureType createPmpDisclosureType() {
        return new PmpDisclosureType();
    }

    /**
     * Create an instance of {@link SearchParametersType }
     * 
     */
    public SearchParametersType createSearchParametersType() {
        return new SearchParametersType();
    }

    /**
     * Create an instance of {@link ErrorExplanationType }
     * 
     */
    public ErrorExplanationType createErrorExplanationType() {
        return new ErrorExplanationType();
    }

    /**
     * Create an instance of {@link DisclosingPmpOptionalType }
     * 
     */
    public DisclosingPmpOptionalType createDisclosingPmpOptionalType() {
        return new DisclosingPmpOptionalType();
    }

    /**
     * Create an instance of {@link SearchingPmpOptionalType }
     * 
     */
    public SearchingPmpOptionalType createSearchingPmpOptionalType() {
        return new SearchingPmpOptionalType();
    }

    /**
     * Create an instance of {@link SearchingPmpType }
     * 
     */
    public SearchingPmpType createSearchingPmpType() {
        return new SearchingPmpType();
    }

    /**
     * Create an instance of {@link DisclosingPmpType }
     * 
     */
    public DisclosingPmpType createDisclosingPmpType() {
        return new DisclosingPmpType();
    }

    /**
     * Create an instance of {@link DisclosingPmpRequestType }
     * 
     */
    public DisclosingPmpRequestType createDisclosingPmpRequestType() {
        return new DisclosingPmpRequestType();
    }

    /**
     * Create an instance of {@link EncryptedDataType }
     * 
     */
    public EncryptedDataType createEncryptedDataType() {
        return new EncryptedDataType();
    }

    /**
     * Create an instance of {@link PmpInterconnectType }
     * 
     */
    public PmpInterconnectType createPmpInterconnectType() {
        return new PmpInterconnectType();
    }

    /**
     * Create an instance of {@link PmpErrorDisclosureType }
     * 
     */
    public PmpErrorDisclosureType createPmpErrorDisclosureType() {
        return new PmpErrorDisclosureType();
    }

    /**
     * Create an instance of {@link DataElementsType }
     * 
     */
    public DataElementsType createDataElementsType() {
        return new DataElementsType();
    }

    /**
     * Create an instance of {@link PmpDisclosuresType }
     * 
     */
    public PmpDisclosuresType createPmpDisclosuresType() {
        return new PmpDisclosuresType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmpDisclosuresType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pmpi.nabp.org/", name = "PmpDisclosures")
    public JAXBElement<PmpDisclosuresType> createPmpDisclosures(PmpDisclosuresType value) {
        return new JAXBElement<PmpDisclosuresType>(_PmpDisclosures_QNAME, PmpDisclosuresType.class, null, value);
    }

}
