//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.nabp.pmpi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PmixDataElementsEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PmixDataElementsEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="/pmix:PMPRequest"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPrescriptionDateRange"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPrescriptionDateRange/pmp:RequestPrescriptionDateRangeBegin"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPrescriptionDateRange/pmp:RequestPrescriptionDateRangeEnd"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonBirthDate"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonBirthDate/nc:Date"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonNamePrefixText"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonGivenName"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonMiddleName"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonSurName"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonNameSuffixText"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonFullName"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSexCode"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSSNIdentification"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSSNIdentification/nc:IdentificationID"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSSNIdentification/nc:IdentificationJurisdictionText"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactTelephoneNumber"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactTelephoneNumber/nc:FullTelephoneNumber"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactTelephoneNumber/nc:FullTelephoneNumber/nc:TelephoneNumberFullID"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationDoingBusinessAsName"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationStreet"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationStreet/nc:StreetFullText"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationCityName"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationStateUSPostalServiceCode"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationPostalCode"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationPostalExtensionCode"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationName"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonStateIssuedIdentifier"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonStateIssuedIdentifier/nc:IdentificationID"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonStateIssuedIdentifier/nc:IdentificationJurisdictionText"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:SpeciesCode"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PatientLocationCode"/>
 *     &lt;enumeration value="/pmix:PMPRequest/pmp:RequestPatient/pmp:PatientNameOfAnimalText"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PmixDataElementsEnumeration")
@XmlEnum
public enum PmixDataElementsEnumeration {

    @XmlEnumValue("/pmix:PMPRequest")
    PMIX_PMP_REQUEST("/pmix:PMPRequest"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPrescriptionDateRange")
    PMIX_PMP_REQUEST_PMP_REQUEST_PRESCRIPTION_DATE_RANGE("/pmix:PMPRequest/pmp:RequestPrescriptionDateRange"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPrescriptionDateRange/pmp:RequestPrescriptionDateRangeBegin")
    PMIX_PMP_REQUEST_PMP_REQUEST_PRESCRIPTION_DATE_RANGE_PMP_REQUEST_PRESCRIPTION_DATE_RANGE_BEGIN("/pmix:PMPRequest/pmp:RequestPrescriptionDateRange/pmp:RequestPrescriptionDateRangeBegin"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPrescriptionDateRange/pmp:RequestPrescriptionDateRangeEnd")
    PMIX_PMP_REQUEST_PMP_REQUEST_PRESCRIPTION_DATE_RANGE_PMP_REQUEST_PRESCRIPTION_DATE_RANGE_END("/pmix:PMPRequest/pmp:RequestPrescriptionDateRange/pmp:RequestPrescriptionDateRangeEnd"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT("/pmix:PMPRequest/pmp:RequestPatient"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonBirthDate")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_BIRTH_DATE("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonBirthDate"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonBirthDate/nc:Date")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_BIRTH_DATE_NC_DATE("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonBirthDate/nc:Date"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_NAME("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonNamePrefixText")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_NAME_NC_PERSON_NAME_PREFIX_TEXT("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonNamePrefixText"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonGivenName")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_NAME_NC_PERSON_GIVEN_NAME("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonGivenName"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonMiddleName")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_NAME_NC_PERSON_MIDDLE_NAME("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonMiddleName"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonSurName")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_NAME_NC_PERSON_SUR_NAME("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonSurName"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonNameSuffixText")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_NAME_NC_PERSON_NAME_SUFFIX_TEXT("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonNameSuffixText"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonFullName")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_NAME_NC_PERSON_FULL_NAME("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonName/nc:PersonFullName"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSexCode")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_SEX_CODE("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSexCode"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSSNIdentification")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_SSN_IDENTIFICATION("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSSNIdentification"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSSNIdentification/nc:IdentificationID")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_SSN_IDENTIFICATION_NC_IDENTIFICATION_ID("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSSNIdentification/nc:IdentificationID"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSSNIdentification/nc:IdentificationJurisdictionText")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_NC_PERSON_SSN_IDENTIFICATION_NC_IDENTIFICATION_JURISDICTION_TEXT("/pmix:PMPRequest/pmp:RequestPatient/nc:PersonSSNIdentification/nc:IdentificationJurisdictionText"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactTelephoneNumber")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_TELEPHONE_NUMBER("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactTelephoneNumber"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactTelephoneNumber/nc:FullTelephoneNumber")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_TELEPHONE_NUMBER_NC_FULL_TELEPHONE_NUMBER("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactTelephoneNumber/nc:FullTelephoneNumber"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactTelephoneNumber/nc:FullTelephoneNumber/nc:TelephoneNumberFullID")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_TELEPHONE_NUMBER_NC_FULL_TELEPHONE_NUMBER_NC_TELEPHONE_NUMBER_FULL_ID("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactTelephoneNumber/nc:FullTelephoneNumber/nc:TelephoneNumberFullID"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationDoingBusinessAsName")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_DOING_BUSINESS_AS_NAME("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationDoingBusinessAsName"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_LOCATION("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_LOCATION_NC_LOCATION_ADDRESS("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_LOCATION_NC_LOCATION_ADDRESS_NC_STRUCTURED_ADDRESS("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationStreet")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_LOCATION_NC_LOCATION_ADDRESS_NC_STRUCTURED_ADDRESS_NC_LOCATION_STREET("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationStreet"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationStreet/nc:StreetFullText")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_LOCATION_NC_LOCATION_ADDRESS_NC_STRUCTURED_ADDRESS_NC_LOCATION_STREET_NC_STREET_FULL_TEXT("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationStreet/nc:StreetFullText"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationCityName")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_LOCATION_NC_LOCATION_ADDRESS_NC_STRUCTURED_ADDRESS_NC_LOCATION_CITY_NAME("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationCityName"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationStateUSPostalServiceCode")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_LOCATION_NC_LOCATION_ADDRESS_NC_STRUCTURED_ADDRESS_NC_LOCATION_STATE_US_POSTAL_SERVICE_CODE("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationStateUSPostalServiceCode"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationPostalCode")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_LOCATION_NC_LOCATION_ADDRESS_NC_STRUCTURED_ADDRESS_NC_LOCATION_POSTAL_CODE("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationPostalCode"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationPostalExtensionCode")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_LOCATION_NC_LOCATION_ADDRESS_NC_STRUCTURED_ADDRESS_NC_LOCATION_POSTAL_EXTENSION_CODE("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationLocation/nc:LocationAddress/nc:StructuredAddress/nc:LocationPostalExtensionCode"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationName")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_PRIMARY_CONTACT_INFORMATION_NC_CONTACT_ENTITY_NC_ENTITY_ORGANIZATION_NC_ORGANIZATION_NAME("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonPrimaryContactInformation/nc:ContactEntity/nc:EntityOrganization/nc:OrganizationName"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonStateIssuedIdentifier")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_STATE_ISSUED_IDENTIFIER("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonStateIssuedIdentifier"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonStateIssuedIdentifier/nc:IdentificationID")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_STATE_ISSUED_IDENTIFIER_NC_IDENTIFICATION_ID("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonStateIssuedIdentifier/nc:IdentificationID"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonStateIssuedIdentifier/nc:IdentificationJurisdictionText")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PERSON_STATE_ISSUED_IDENTIFIER_NC_IDENTIFICATION_JURISDICTION_TEXT("/pmix:PMPRequest/pmp:RequestPatient/pmp:PersonStateIssuedIdentifier/nc:IdentificationJurisdictionText"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:SpeciesCode")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_SPECIES_CODE("/pmix:PMPRequest/pmp:RequestPatient/pmp:SpeciesCode"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PatientLocationCode")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PATIENT_LOCATION_CODE("/pmix:PMPRequest/pmp:RequestPatient/pmp:PatientLocationCode"),
    @XmlEnumValue("/pmix:PMPRequest/pmp:RequestPatient/pmp:PatientNameOfAnimalText")
    PMIX_PMP_REQUEST_PMP_REQUEST_PATIENT_PMP_PATIENT_NAME_OF_ANIMAL_TEXT("/pmix:PMPRequest/pmp:RequestPatient/pmp:PatientNameOfAnimalText");
    private final String value;

    PmixDataElementsEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PmixDataElementsEnumeration fromValue(String v) {
        for (PmixDataElementsEnumeration c: PmixDataElementsEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
