/*
   Copyright 2013 Collaborative For Universal Health (C4UH), Logicoy Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
  */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.nabp.pmpi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PmpDisclosureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PmpDisclosureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://pmpi.nabp.org/}DisclosureResponseTypeEnumeration"/>
 *         &lt;element name="InterconnectSearchId" type="{http://pmpi.nabp.org/}InterconnectSearchIdType"/>
 *         &lt;element name="InterconnectDisclosureId" type="{http://pmpi.nabp.org/}InterconnectDisclosureIdType"/>
 *         &lt;element name="SearchingPmp" type="{http://pmpi.nabp.org/}SearchingPmpType"/>
 *         &lt;element name="DisclosingPmp" type="{http://pmpi.nabp.org/}DisclosingPmpType"/>
 *         &lt;choice>
 *           &lt;element name="EncryptedData" type="{http://pmpi.nabp.org/}EncryptedDataType"/>
 *           &lt;element name="PlaintextData" type="{http://pmpi.nabp.org/}PlaintextDataType" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PmpDisclosureType", propOrder = {
    "type",
    "interconnectSearchId",
    "interconnectDisclosureId",
    "searchingPmp",
    "disclosingPmp",
    "encryptedData",
    "plaintextData"
})
public class PmpDisclosureType {

    @XmlElement(name = "Type", required = true)
    protected DisclosureResponseTypeEnumeration type;
    @XmlElement(name = "InterconnectSearchId", required = true)
    protected BigInteger interconnectSearchId;
    @XmlElement(name = "InterconnectDisclosureId", required = true)
    protected BigInteger interconnectDisclosureId;
    @XmlElement(name = "SearchingPmp", required = true)
    protected SearchingPmpType searchingPmp;
    @XmlElement(name = "DisclosingPmp", required = true)
    protected DisclosingPmpType disclosingPmp;
    @XmlElement(name = "EncryptedData")
    protected EncryptedDataType encryptedData;
    @XmlElement(name = "PlaintextData")
    protected String plaintextData;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link DisclosureResponseTypeEnumeration }
     *     
     */
    public DisclosureResponseTypeEnumeration getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisclosureResponseTypeEnumeration }
     *     
     */
    public void setType(DisclosureResponseTypeEnumeration value) {
        this.type = value;
    }

    /**
     * Gets the value of the interconnectSearchId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInterconnectSearchId() {
        return interconnectSearchId;
    }

    /**
     * Sets the value of the interconnectSearchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInterconnectSearchId(BigInteger value) {
        this.interconnectSearchId = value;
    }

    /**
     * Gets the value of the interconnectDisclosureId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInterconnectDisclosureId() {
        return interconnectDisclosureId;
    }

    /**
     * Sets the value of the interconnectDisclosureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInterconnectDisclosureId(BigInteger value) {
        this.interconnectDisclosureId = value;
    }

    /**
     * Gets the value of the searchingPmp property.
     * 
     * @return
     *     possible object is
     *     {@link SearchingPmpType }
     *     
     */
    public SearchingPmpType getSearchingPmp() {
        return searchingPmp;
    }

    /**
     * Sets the value of the searchingPmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchingPmpType }
     *     
     */
    public void setSearchingPmp(SearchingPmpType value) {
        this.searchingPmp = value;
    }

    /**
     * Gets the value of the disclosingPmp property.
     * 
     * @return
     *     possible object is
     *     {@link DisclosingPmpType }
     *     
     */
    public DisclosingPmpType getDisclosingPmp() {
        return disclosingPmp;
    }

    /**
     * Sets the value of the disclosingPmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisclosingPmpType }
     *     
     */
    public void setDisclosingPmp(DisclosingPmpType value) {
        this.disclosingPmp = value;
    }

    /**
     * Gets the value of the encryptedData property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptedDataType }
     *     
     */
    public EncryptedDataType getEncryptedData() {
        return encryptedData;
    }

    /**
     * Sets the value of the encryptedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptedDataType }
     *     
     */
    public void setEncryptedData(EncryptedDataType value) {
        this.encryptedData = value;
    }

    /**
     * Gets the value of the plaintextData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaintextData() {
        return plaintextData;
    }

    /**
     * Sets the value of the plaintextData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaintextData(String value) {
        this.plaintextData = value;
    }

}
