//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:32 PM IST 
//


package org.nabp.pmpi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SearchingPmp" type="{http://pmpi.nabp.org/}SearchingPmpType"/>
 *         &lt;element name="DisclosingPmps" type="{http://pmpi.nabp.org/}DisclosingPmpsType"/>
 *         &lt;element name="SearchParameters" type="{http://pmpi.nabp.org/}SearchParametersType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchRequestType", propOrder = {
    "searchingPmp",
    "disclosingPmps",
    "searchParameters"
})
public class SearchRequestType {

    @XmlElement(name = "SearchingPmp", required = true)
    protected SearchingPmpType searchingPmp;
    @XmlElement(name = "DisclosingPmps", required = true)
    protected DisclosingPmpsType disclosingPmps;
    @XmlElement(name = "SearchParameters", required = true)
    protected SearchParametersType searchParameters;

    /**
     * Gets the value of the searchingPmp property.
     * 
     * @return
     *     possible object is
     *     {@link SearchingPmpType }
     *     
     */
    public SearchingPmpType getSearchingPmp() {
        return searchingPmp;
    }

    /**
     * Sets the value of the searchingPmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchingPmpType }
     *     
     */
    public void setSearchingPmp(SearchingPmpType value) {
        this.searchingPmp = value;
    }

    /**
     * Gets the value of the disclosingPmps property.
     * 
     * @return
     *     possible object is
     *     {@link DisclosingPmpsType }
     *     
     */
    public DisclosingPmpsType getDisclosingPmps() {
        return disclosingPmps;
    }

    /**
     * Sets the value of the disclosingPmps property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisclosingPmpsType }
     *     
     */
    public void setDisclosingPmps(DisclosingPmpsType value) {
        this.disclosingPmps = value;
    }

    /**
     * Gets the value of the searchParameters property.
     * 
     * @return
     *     possible object is
     *     {@link SearchParametersType }
     *     
     */
    public SearchParametersType getSearchParameters() {
        return searchParameters;
    }

    /**
     * Sets the value of the searchParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchParametersType }
     *     
     */
    public void setSearchParameters(SearchParametersType value) {
        this.searchParameters = value;
    }

}
