//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.nabp.pmpi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchingPmpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchingPmpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InterconnectPmpId" type="{http://pmpi.nabp.org/}InterconnectPmpIdType"/>
 *         &lt;element name="PmpUserRole" type="{http://pmpi.nabp.org/}UserRoleTypeEnumeration"/>
 *         &lt;element name="PmpSearchId" type="{http://pmpi.nabp.org/}PmpSearchIdType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchingPmpType", propOrder = {
    "interconnectPmpId",
    "pmpUserRole",
    "pmpSearchId"
})
public class SearchingPmpType {

    @XmlElement(name = "InterconnectPmpId", required = true)
    protected BigInteger interconnectPmpId;
    @XmlElement(name = "PmpUserRole", required = true)
    protected UserRoleTypeEnumeration pmpUserRole;
    @XmlElement(name = "PmpSearchId")
    protected String pmpSearchId;

    /**
     * Gets the value of the interconnectPmpId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInterconnectPmpId() {
        return interconnectPmpId;
    }

    /**
     * Sets the value of the interconnectPmpId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInterconnectPmpId(BigInteger value) {
        this.interconnectPmpId = value;
    }

    /**
     * Gets the value of the pmpUserRole property.
     * 
     * @return
     *     possible object is
     *     {@link UserRoleTypeEnumeration }
     *     
     */
    public UserRoleTypeEnumeration getPmpUserRole() {
        return pmpUserRole;
    }

    /**
     * Sets the value of the pmpUserRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserRoleTypeEnumeration }
     *     
     */
    public void setPmpUserRole(UserRoleTypeEnumeration value) {
        this.pmpUserRole = value;
    }

    /**
     * Gets the value of the pmpSearchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmpSearchId() {
        return pmpSearchId;
    }

    /**
     * Sets the value of the pmpSearchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmpSearchId(String value) {
        this.pmpSearchId = value;
    }

}
