/*
   Copyright 2013 Collaborative For Universal Health (C4UH), Logicoy Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
  */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.nabp.pmpi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchParametersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchParametersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataElements" type="{http://pmpi.nabp.org/}DataElementsType"/>
 *         &lt;element name="AesEncryptedData" type="{http://pmpi.nabp.org/}AesEncryptedDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchParametersType", propOrder = {
    "dataElements",
    "aesEncryptedData"
})
public class SearchParametersType {

    @XmlElement(name = "DataElements", required = true)
    protected DataElementsType dataElements;
    @XmlElement(name = "AesEncryptedData", required = true)
    protected String aesEncryptedData;

    /**
     * Gets the value of the dataElements property.
     * 
     * @return
     *     possible object is
     *     {@link DataElementsType }
     *     
     */
    public DataElementsType getDataElements() {
        return dataElements;
    }

    /**
     * Sets the value of the dataElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataElementsType }
     *     
     */
    public void setDataElements(DataElementsType value) {
        this.dataElements = value;
    }

    /**
     * Gets the value of the aesEncryptedData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAesEncryptedData() {
        return aesEncryptedData;
    }

    /**
     * Sets the value of the aesEncryptedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAesEncryptedData(String value) {
        this.aesEncryptedData = value;
    }

}
