//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.niem._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.niem.structures._2.ComplexObjectType;
import org.ijis.xml.niem._2_0.extension.PatientType;
import org.ijis.xml.niem._2_0.extension.RequestPrescriptionDateRangeType;


/**
 * A request received from the PMP Requesting Agency 
 * 
 * <p>Java class for PMPRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PMPRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://niem.gov/niem/structures/2.0}ComplexObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}RequestPrescriptionDateRange" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}RequestPatient" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PMPRequestType", propOrder = {
    "requestPrescriptionDateRange",
    "requestPatient"
})
public class PMPRequestType
    extends ComplexObjectType
{

    @XmlElement(name = "RequestPrescriptionDateRange", namespace = "http://xml.ijis.org/niem/2.0/extension", nillable = true)
    protected List<RequestPrescriptionDateRangeType> requestPrescriptionDateRange;
    @XmlElement(name = "RequestPatient", namespace = "http://xml.ijis.org/niem/2.0/extension", nillable = true)
    protected List<PatientType> requestPatient;

    /**
     * Gets the value of the requestPrescriptionDateRange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestPrescriptionDateRange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestPrescriptionDateRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestPrescriptionDateRangeType }
     * 
     * 
     */
    public List<RequestPrescriptionDateRangeType> getRequestPrescriptionDateRange() {
        if (requestPrescriptionDateRange == null) {
            requestPrescriptionDateRange = new ArrayList<RequestPrescriptionDateRangeType>();
        }
        return this.requestPrescriptionDateRange;
    }

    /**
     * Gets the value of the requestPatient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestPatient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestPatient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatientType }
     * 
     * 
     */
    public List<PatientType> getRequestPatient() {
        if (requestPatient == null) {
            requestPatient = new ArrayList<PatientType>();
        }
        return this.requestPatient;
    }

}
