//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package gov.niem.niem.fbi._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DrugMeasurementCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DrugMeasurementCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="DU"/>
 *     &lt;enumeration value="FO"/>
 *     &lt;enumeration value="GL"/>
 *     &lt;enumeration value="GM"/>
 *     &lt;enumeration value="KG"/>
 *     &lt;enumeration value="LB"/>
 *     &lt;enumeration value="LT"/>
 *     &lt;enumeration value="ML"/>
 *     &lt;enumeration value="NP"/>
 *     &lt;enumeration value="OZ"/>
 *     &lt;enumeration value="XX"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DrugMeasurementCodeSimpleType")
@XmlEnum
public enum DrugMeasurementCodeSimpleType {

    DU,
    FO,
    GL,
    GM,
    KG,
    LB,
    LT,
    ML,
    NP,
    OZ,
    XX;

    public String value() {
        return name();
    }

    public static DrugMeasurementCodeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
