//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.niem._2_0.extension;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import gov.niem.niem.niem_core._2.IdentificationType;
import gov.niem.niem.niem_core._2.TextType;
import gov.niem.niem.proxy.xsd._2.Decimal;
import gov.niem.niem.proxy.xsd._2.NonNegativeInteger;
import gov.niem.niem.structures._2.ComplexObjectType;


/**
 * Ingredients that make up a compound drug.
 * 			
 * 
 * <p>Java class for CompoundDrugIngredientType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompoundDrugIngredientType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://niem.gov/niem/structures/2.0}ComplexObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}CompoundDrugIngredientSequenceNumber" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}CompoundDrugIngredientProductIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}CompoundDrugIngredientProductNameText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}CompoundDrugIngredientStrengthText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}CompoundDrugIngredientDEAClassScheduleText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}IngredientQuantity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}CompoundDrugIngredientDrugDosageUnitsCode" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompoundDrugIngredientType", propOrder = {
    "compoundDrugIngredientSequenceNumber",
    "compoundDrugIngredientProductIdentifier",
    "compoundDrugIngredientProductNameText",
    "compoundDrugIngredientStrengthText",
    "compoundDrugIngredientDEAClassScheduleText",
    "ingredientQuantity",
    "compoundDrugIngredientDrugDosageUnitsCode"
})
public class CompoundDrugIngredientType
    extends ComplexObjectType
{

    @XmlElement(name = "CompoundDrugIngredientSequenceNumber", nillable = true)
    protected List<NonNegativeInteger> compoundDrugIngredientSequenceNumber;
    @XmlElementRef(name = "CompoundDrugIngredientProductIdentifier", namespace = "http://xml.ijis.org/niem/2.0/extension", type = JAXBElement.class)
    protected List<JAXBElement<?>> compoundDrugIngredientProductIdentifier;
    @XmlElement(name = "CompoundDrugIngredientProductNameText", nillable = true)
    protected List<TextType> compoundDrugIngredientProductNameText;
    @XmlElement(name = "CompoundDrugIngredientStrengthText", nillable = true)
    protected List<TextType> compoundDrugIngredientStrengthText;
    @XmlElement(name = "CompoundDrugIngredientDEAClassScheduleText", nillable = true)
    protected List<TextType> compoundDrugIngredientDEAClassScheduleText;
    @XmlElement(name = "IngredientQuantity", nillable = true)
    protected List<Decimal> ingredientQuantity;
    @XmlElement(name = "CompoundDrugIngredientDrugDosageUnitsCode", nillable = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected List<String> compoundDrugIngredientDrugDosageUnitsCode;

    /**
     * Gets the value of the compoundDrugIngredientSequenceNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compoundDrugIngredientSequenceNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompoundDrugIngredientSequenceNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonNegativeInteger }
     * 
     * 
     */
    public List<NonNegativeInteger> getCompoundDrugIngredientSequenceNumber() {
        if (compoundDrugIngredientSequenceNumber == null) {
            compoundDrugIngredientSequenceNumber = new ArrayList<NonNegativeInteger>();
        }
        return this.compoundDrugIngredientSequenceNumber;
    }

    /**
     * Gets the value of the compoundDrugIngredientProductIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compoundDrugIngredientProductIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompoundDrugIngredientProductIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}
     * {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}
     * {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}
     * {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}
     * {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getCompoundDrugIngredientProductIdentifier() {
        if (compoundDrugIngredientProductIdentifier == null) {
            compoundDrugIngredientProductIdentifier = new ArrayList<JAXBElement<?>>();
        }
        return this.compoundDrugIngredientProductIdentifier;
    }

    /**
     * Gets the value of the compoundDrugIngredientProductNameText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compoundDrugIngredientProductNameText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompoundDrugIngredientProductNameText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getCompoundDrugIngredientProductNameText() {
        if (compoundDrugIngredientProductNameText == null) {
            compoundDrugIngredientProductNameText = new ArrayList<TextType>();
        }
        return this.compoundDrugIngredientProductNameText;
    }

    /**
     * Gets the value of the compoundDrugIngredientStrengthText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compoundDrugIngredientStrengthText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompoundDrugIngredientStrengthText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getCompoundDrugIngredientStrengthText() {
        if (compoundDrugIngredientStrengthText == null) {
            compoundDrugIngredientStrengthText = new ArrayList<TextType>();
        }
        return this.compoundDrugIngredientStrengthText;
    }

    /**
     * Gets the value of the compoundDrugIngredientDEAClassScheduleText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compoundDrugIngredientDEAClassScheduleText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompoundDrugIngredientDEAClassScheduleText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getCompoundDrugIngredientDEAClassScheduleText() {
        if (compoundDrugIngredientDEAClassScheduleText == null) {
            compoundDrugIngredientDEAClassScheduleText = new ArrayList<TextType>();
        }
        return this.compoundDrugIngredientDEAClassScheduleText;
    }

    /**
     * Gets the value of the ingredientQuantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ingredientQuantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIngredientQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Decimal }
     * 
     * 
     */
    public List<Decimal> getIngredientQuantity() {
        if (ingredientQuantity == null) {
            ingredientQuantity = new ArrayList<Decimal>();
        }
        return this.ingredientQuantity;
    }

    /**
     * Gets the value of the compoundDrugIngredientDrugDosageUnitsCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compoundDrugIngredientDrugDosageUnitsCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompoundDrugIngredientDrugDosageUnitsCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCompoundDrugIngredientDrugDosageUnitsCode() {
        if (compoundDrugIngredientDrugDosageUnitsCode == null) {
            compoundDrugIngredientDrugDosageUnitsCode = new ArrayList<String>();
        }
        return this.compoundDrugIngredientDrugDosageUnitsCode;
    }

}
