/*
   Copyright 2013 Collaborative For Universal Health (C4UH), Logicoy Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
  */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.niem._2_0.extension;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.niem.niem_core._2.IdentificationType;
import gov.niem.niem.niem_core._2.OrganizationType;
import gov.niem.niem.niem_core._2.TextType;


/**
 * <p>Java class for DispenserType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispenserType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://niem.gov/niem/niem-core/2.0}OrganizationType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}NPIIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}DEANumberIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}StateLicenseIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}NCPDPIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ContactNameText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ChainSiteIDText" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispenserType", propOrder = {
    "npiIdentifier",
    "deaNumberIdentifier",
    "stateLicenseIdentifier",
    "ncpdpIdentifier",
    "contactNameText",
    "chainSiteIDText"
})
public class DispenserType
    extends OrganizationType
{

    @XmlElement(name = "NPIIdentifier", nillable = true)
    protected List<IdentificationType> npiIdentifier;
    @XmlElement(name = "DEANumberIdentifier", nillable = true)
    protected List<IdentificationType> deaNumberIdentifier;
    @XmlElement(name = "StateLicenseIdentifier", nillable = true)
    protected List<IdentificationType> stateLicenseIdentifier;
    @XmlElement(name = "NCPDPIdentifier", nillable = true)
    protected List<IdentificationType> ncpdpIdentifier;
    @XmlElement(name = "ContactNameText", nillable = true)
    protected List<TextType> contactNameText;
    @XmlElement(name = "ChainSiteIDText", nillable = true)
    protected List<TextType> chainSiteIDText;

    /**
     * Gets the value of the npiIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the npiIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNPIIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getNPIIdentifier() {
        if (npiIdentifier == null) {
            npiIdentifier = new ArrayList<IdentificationType>();
        }
        return this.npiIdentifier;
    }

    /**
     * Gets the value of the deaNumberIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deaNumberIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDEANumberIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getDEANumberIdentifier() {
        if (deaNumberIdentifier == null) {
            deaNumberIdentifier = new ArrayList<IdentificationType>();
        }
        return this.deaNumberIdentifier;
    }

    /**
     * Gets the value of the stateLicenseIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stateLicenseIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStateLicenseIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getStateLicenseIdentifier() {
        if (stateLicenseIdentifier == null) {
            stateLicenseIdentifier = new ArrayList<IdentificationType>();
        }
        return this.stateLicenseIdentifier;
    }

    /**
     * Gets the value of the ncpdpIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ncpdpIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNCPDPIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getNCPDPIdentifier() {
        if (ncpdpIdentifier == null) {
            ncpdpIdentifier = new ArrayList<IdentificationType>();
        }
        return this.ncpdpIdentifier;
    }

    /**
     * Gets the value of the contactNameText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactNameText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactNameText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getContactNameText() {
        if (contactNameText == null) {
            contactNameText = new ArrayList<TextType>();
        }
        return this.contactNameText;
    }

    /**
     * Gets the value of the chainSiteIDText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chainSiteIDText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChainSiteIDText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getChainSiteIDText() {
        if (chainSiteIDText == null) {
            chainSiteIDText = new ArrayList<TextType>();
        }
        return this.chainSiteIDText;
    }

}
