//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.niem._2_0.extension;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import gov.niem.niem.niem_core._2.ContactInformationType;
import gov.niem.niem.niem_core._2.DateType;
import gov.niem.niem.niem_core._2.IdentificationType;
import gov.niem.niem.niem_core._2.OrganizationType;
import gov.niem.niem.niem_core._2.PersonType;
import gov.niem.niem.niem_core._2.TextType;
import gov.niem.niem.proxy.xsd._2.Boolean;
import gov.niem.niem.proxy.xsd._2.Date;
import gov.niem.niem.proxy.xsd._2.Decimal;
import gov.niem.niem.proxy.xsd._2.NonNegativeInteger;
import gov.niem.niem.proxy.xsd._2.Time;
import org.ijis.xml.pmpcode.FileTypeCodeType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ijis.xml.niem._2_0.extension package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PrescriptionElectronicReferenceNumberText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PrescriptionElectronicReferenceNumberText");
    private final static QName _Dispenser_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "Dispenser");
    private final static QName _MessageText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "MessageText");
    private final static QName _CompoundDrugIngredientUPNProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientUPNProductIdentifier");
    private final static QName _Person_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "Person");
    private final static QName _SpeciesCode_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "SpeciesCode");
    private final static QName _ReportExecutionDate_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "ReportExecutionDate");
    private final static QName _DrugUPNProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugUPNProductIdentifier");
    private final static QName _DrugStrengthText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugStrengthText");
    private final static QName _PersonIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonIdentifier");
    private final static QName _DrugProductNameText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugProductNameText");
    private final static QName _RequestPatient_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "RequestPatient");
    private final static QName _PersonSocialSecurityNumberIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonSocialSecurityNumberIdentifier");
    private final static QName _MethodOfPaymentCode_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "MethodOfPaymentCode");
    private final static QName _DaysSupplyCount_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DaysSupplyCount");
    private final static QName _PharmacyReportingPrescriptionReport_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PharmacyReportingPrescriptionReport");
    private final static QName _RequestPrescriptionDateRangeBegin_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "RequestPrescriptionDateRangeBegin");
    private final static QName _DrugUPCProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugUPCProductIdentifier");
    private final static QName _PrescriptionWrittenDate_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PrescriptionWrittenDate");
    private final static QName _CompoundDrugIngredientProductNameText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientProductNameText");
    private final static QName _CompoundDrugIngredientHRIProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientHRIProductIdentifier");
    private final static QName _PrescriptionNumberText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PrescriptionNumberText");
    private final static QName _PrescriptionSoldDate_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PrescriptionSoldDate");
    private final static QName _PrescriptionDrug_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PrescriptionDrug");
    private final static QName _CompoundDrugIngredientProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientProductIdentifier");
    private final static QName _CompoundDrugIngredientStrengthText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientStrengthText");
    private final static QName _PMPPresentationDocument_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PMPPresentationDocument");
    private final static QName _TransmissionFormOfRxOriginCode_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "TransmissionFormOfRxOriginCode");
    private final static QName _CompoundDrugIngredientDrugDosageUnitsCode_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientDrugDosageUnitsCode");
    private final static QName _DocumentPublicationTime_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DocumentPublicationTime");
    private final static QName _RequestDispenser_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "RequestDispenser");
    private final static QName _RequestPrescriptionDateRange_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "RequestPrescriptionDateRange");
    private final static QName _PersonStateIssuedIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonStateIssuedIdentifier");
    private final static QName _PartialFillIndicator_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PartialFillIndicator");
    private final static QName _PatientNameOfAnimalText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PatientNameOfAnimalText");
    private final static QName _CompoundDrugIngredientSequenceNumber_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientSequenceNumber");
    private final static QName _PMPDocumentAugmentation_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PMPDocumentAugmentation");
    private final static QName _PersonOtherIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonOtherIdentifier");
    private final static QName _DrugDosageUnitsCode_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugDosageUnitsCode");
    private final static QName _CompoundDrugIngredientDINProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientDINProductIdentifier");
    private final static QName _PersonPickingUpRx_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonPickingUpRx");
    private final static QName _Prescription_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "Prescription");
    private final static QName _RefillsAuthorizedCount_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "RefillsAuthorizedCount");
    private final static QName _IngredientQuantity_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "IngredientQuantity");
    private final static QName _PrescriberDEANumberSuffixText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PrescriberDEANumberSuffixText");
    private final static QName _DrugRefillNumberCount_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugRefillNumberCount");
    private final static QName _PrescriptionFilledDate_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PrescriptionFilledDate");
    private final static QName _CompoundDrugIngredient_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredient");
    private final static QName _Patient_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "Patient");
    private final static QName _PersonMilitaryIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonMilitaryIdentifier");
    private final static QName _TransactionTypeCode_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "TransactionTypeCode");
    private final static QName _DrugProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugProductIdentifier");
    private final static QName _InformationSourceEntityNameText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "InformationSourceEntityNameText");
    private final static QName _ContactNameText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "ContactNameText");
    private final static QName _Document_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "Document");
    private final static QName _StateLicenseIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "StateLicenseIdentifier");
    private final static QName _ReportDateRange_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "ReportDateRange");
    private final static QName _Pharmacist_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "Pharmacist");
    private final static QName _PrescriptionForReporting_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PrescriptionForReporting");
    private final static QName _FileTypeCode_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "FileTypeCode");
    private final static QName _NCPDPIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "NCPDPIdentifier");
    private final static QName _DrugDINProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugDINProductIdentifier");
    private final static QName _DrugNDCProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugNDCProductIdentifier");
    private final static QName _RelationshipToPatientCode_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "RelationshipToPatientCode");
    private final static QName _PersonPrimaryContactInformation_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonPrimaryContactInformation");
    private final static QName _Prescriber_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "Prescriber");
    private final static QName _PersonUniqueSystemIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonUniqueSystemIdentifier");
    private final static QName _PatientLocationCode_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PatientLocationCode");
    private final static QName _DrugCPDProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugCPDProductIdentifier");
    private final static QName _CompoundDrugIngredientDEAClassScheduleText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientDEAClassScheduleText");
    private final static QName _ReportDateRangeBegin_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "ReportDateRangeBegin");
    private final static QName _ReportDateRangeEnd_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "ReportDateRangeEnd");
    private final static QName _RequestResponsePrescriptionReport_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "RequestResponsePrescriptionReport");
    private final static QName _VersionReleaseNumberText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "VersionReleaseNumberText");
    private final static QName _RoutingNumber_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "RoutingNumber");
    private final static QName _DispensedQuantity_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DispensedQuantity");
    private final static QName _ResponseIDText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "ResponseIDText");
    private final static QName _NPIIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "NPIIdentifier");
    private final static QName _DEAClassScheduleText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DEAClassScheduleText");
    private final static QName _ReportingStatusCode_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "ReportingStatusCode");
    private final static QName _RequestPrescriptionDateRangeEnd_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "RequestPrescriptionDateRangeEnd");
    private final static QName _PersonTribalIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonTribalIdentifier");
    private final static QName _DrugHRIProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugHRIProductIdentifier");
    private final static QName _DEANumberIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DEANumberIdentifier");
    private final static QName _CompoundDrugIngredientNDCProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientNDCProductIdentifier");
    private final static QName _CompoundDrugIngredientUPCProductIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "CompoundDrugIngredientUPCProductIdentifier");
    private final static QName _ChainSiteIDText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "ChainSiteIDText");
    private final static QName _PrescriptionReport_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PrescriptionReport");
    private final static QName _PersonPassportIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonPassportIdentifier");
    private final static QName _ReportExecutionTime_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "ReportExecutionTime");
    private final static QName _PrescriptionNormCodeText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PrescriptionNormCodeText");
    private final static QName _Organization_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "Organization");
    private final static QName _StateIssuedRxSerialNumberIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "StateIssuedRxSerialNumberIdentifier");
    private final static QName _TransactionControlNumberText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "TransactionControlNumberText");
    private final static QName _DrugUnitOfMeasureText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "DrugUnitOfMeasureText");
    private final static QName _RequestPrescriber_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "RequestPrescriber");
    private final static QName _PersonDriverLicenseIdentifier_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "PersonDriverLicenseIdentifier");
    private final static QName _UniqueInformationSourceIDText_QNAME = new QName("http://xml.ijis.org/niem/2.0/extension", "UniqueInformationSourceIDText");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ijis.xml.niem._2_0.extension
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PMPDocumentAugmentationType }
     * 
     */
    public PMPDocumentAugmentationType createPMPDocumentAugmentationType() {
        return new PMPDocumentAugmentationType();
    }

    /**
     * Create an instance of {@link PrescriptionDrugType }
     * 
     */
    public PrescriptionDrugType createPrescriptionDrugType() {
        return new PrescriptionDrugType();
    }

    /**
     * Create an instance of {@link RequestResponsePrescriptionReportType }
     * 
     */
    public RequestResponsePrescriptionReportType createRequestResponsePrescriptionReportType() {
        return new RequestResponsePrescriptionReportType();
    }

    /**
     * Create an instance of {@link ReportDateRangeType }
     * 
     */
    public ReportDateRangeType createReportDateRangeType() {
        return new ReportDateRangeType();
    }

    /**
     * Create an instance of {@link PersonPickingUpRxType }
     * 
     */
    public PersonPickingUpRxType createPersonPickingUpRxType() {
        return new PersonPickingUpRxType();
    }

    /**
     * Create an instance of {@link PharmacyReportingPrescriptionReportType }
     * 
     */
    public PharmacyReportingPrescriptionReportType createPharmacyReportingPrescriptionReportType() {
        return new PharmacyReportingPrescriptionReportType();
    }

    /**
     * Create an instance of {@link RequestPrescriptionDateRangeType }
     * 
     */
    public RequestPrescriptionDateRangeType createRequestPrescriptionDateRangeType() {
        return new RequestPrescriptionDateRangeType();
    }

    /**
     * Create an instance of {@link PharmacistType }
     * 
     */
    public PharmacistType createPharmacistType() {
        return new PharmacistType();
    }

    /**
     * Create an instance of {@link PrescriberType }
     * 
     */
    public PrescriberType createPrescriberType() {
        return new PrescriberType();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientType();
    }

    /**
     * Create an instance of {@link DispenserType }
     * 
     */
    public DispenserType createDispenserType() {
        return new DispenserType();
    }

    /**
     * Create an instance of {@link CompoundDrugIngredientType }
     * 
     */
    public CompoundDrugIngredientType createCompoundDrugIngredientType() {
        return new CompoundDrugIngredientType();
    }

    /**
     * Create an instance of {@link PrescriptionForReportingType }
     * 
     */
    public PrescriptionForReportingType createPrescriptionForReportingType() {
        return new PrescriptionForReportingType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link PrescriptionType }
     * 
     */
    public PrescriptionType createPrescriptionType() {
        return new PrescriptionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PrescriptionElectronicReferenceNumberText")
    public JAXBElement<TextType> createPrescriptionElectronicReferenceNumberText(TextType value) {
        return new JAXBElement<TextType>(_PrescriptionElectronicReferenceNumberText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DispenserType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "Dispenser")
    public JAXBElement<DispenserType> createDispenser(DispenserType value) {
        return new JAXBElement<DispenserType>(_Dispenser_QNAME, DispenserType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "MessageText")
    public JAXBElement<TextType> createMessageText(TextType value) {
        return new JAXBElement<TextType>(_MessageText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientUPNProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "CompoundDrugIngredientProductIdentifier")
    public JAXBElement<IdentificationType> createCompoundDrugIngredientUPNProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_CompoundDrugIngredientUPNProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "Person")
    public JAXBElement<PersonType> createPerson(PersonType value) {
        return new JAXBElement<PersonType>(_Person_QNAME, PersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "SpeciesCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSpeciesCode(String value) {
        return new JAXBElement<String>(_SpeciesCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "ReportExecutionDate", substitutionHeadNamespace = "http://niem.gov/niem/niem-core/2.0", substitutionHeadName = "DateRepresentation")
    public JAXBElement<Date> createReportExecutionDate(Date value) {
        return new JAXBElement<Date>(_ReportExecutionDate_QNAME, Date.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugUPNProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "DrugProductIdentifier")
    public JAXBElement<IdentificationType> createDrugUPNProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_DrugUPNProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugStrengthText")
    public JAXBElement<TextType> createDrugStrengthText(TextType value) {
        return new JAXBElement<TextType>(_DrugStrengthText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonIdentifier")
    public JAXBElement<Object> createPersonIdentifier(Object value) {
        return new JAXBElement<Object>(_PersonIdentifier_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugProductNameText")
    public JAXBElement<TextType> createDrugProductNameText(TextType value) {
        return new JAXBElement<TextType>(_DrugProductNameText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "RequestPatient")
    public JAXBElement<PatientType> createRequestPatient(PatientType value) {
        return new JAXBElement<PatientType>(_RequestPatient_QNAME, PatientType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonSocialSecurityNumberIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "PersonIdentifier")
    public JAXBElement<IdentificationType> createPersonSocialSecurityNumberIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_PersonSocialSecurityNumberIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "MethodOfPaymentCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMethodOfPaymentCode(String value) {
        return new JAXBElement<String>(_MethodOfPaymentCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DaysSupplyCount")
    public JAXBElement<NonNegativeInteger> createDaysSupplyCount(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_DaysSupplyCount_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PharmacyReportingPrescriptionReportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PharmacyReportingPrescriptionReport", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "PrescriptionReport")
    public JAXBElement<PharmacyReportingPrescriptionReportType> createPharmacyReportingPrescriptionReport(PharmacyReportingPrescriptionReportType value) {
        return new JAXBElement<PharmacyReportingPrescriptionReportType>(_PharmacyReportingPrescriptionReport_QNAME, PharmacyReportingPrescriptionReportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "RequestPrescriptionDateRangeBegin", substitutionHeadNamespace = "http://niem.gov/niem/niem-core/2.0", substitutionHeadName = "DateRepresentation")
    public JAXBElement<Date> createRequestPrescriptionDateRangeBegin(Date value) {
        return new JAXBElement<Date>(_RequestPrescriptionDateRangeBegin_QNAME, Date.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugUPCProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "DrugProductIdentifier")
    public JAXBElement<IdentificationType> createDrugUPCProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_DrugUPCProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PrescriptionWrittenDate")
    public JAXBElement<DateType> createPrescriptionWrittenDate(DateType value) {
        return new JAXBElement<DateType>(_PrescriptionWrittenDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientProductNameText")
    public JAXBElement<TextType> createCompoundDrugIngredientProductNameText(TextType value) {
        return new JAXBElement<TextType>(_CompoundDrugIngredientProductNameText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientHRIProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "CompoundDrugIngredientProductIdentifier")
    public JAXBElement<IdentificationType> createCompoundDrugIngredientHRIProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_CompoundDrugIngredientHRIProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PrescriptionNumberText")
    public JAXBElement<TextType> createPrescriptionNumberText(TextType value) {
        return new JAXBElement<TextType>(_PrescriptionNumberText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PrescriptionSoldDate")
    public JAXBElement<Date> createPrescriptionSoldDate(Date value) {
        return new JAXBElement<Date>(_PrescriptionSoldDate_QNAME, Date.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrescriptionDrugType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PrescriptionDrug")
    public JAXBElement<PrescriptionDrugType> createPrescriptionDrug(PrescriptionDrugType value) {
        return new JAXBElement<PrescriptionDrugType>(_PrescriptionDrug_QNAME, PrescriptionDrugType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientProductIdentifier")
    public JAXBElement<Object> createCompoundDrugIngredientProductIdentifier(Object value) {
        return new JAXBElement<Object>(_CompoundDrugIngredientProductIdentifier_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientStrengthText")
    public JAXBElement<TextType> createCompoundDrugIngredientStrengthText(TextType value) {
        return new JAXBElement<TextType>(_CompoundDrugIngredientStrengthText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PMPPresentationDocument")
    public JAXBElement<DocumentType> createPMPPresentationDocument(DocumentType value) {
        return new JAXBElement<DocumentType>(_PMPPresentationDocument_QNAME, DocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "TransmissionFormOfRxOriginCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTransmissionFormOfRxOriginCode(String value) {
        return new JAXBElement<String>(_TransmissionFormOfRxOriginCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientDrugDosageUnitsCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCompoundDrugIngredientDrugDosageUnitsCode(String value) {
        return new JAXBElement<String>(_CompoundDrugIngredientDrugDosageUnitsCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Time }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DocumentPublicationTime")
    public JAXBElement<Time> createDocumentPublicationTime(Time value) {
        return new JAXBElement<Time>(_DocumentPublicationTime_QNAME, Time.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DispenserType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "RequestDispenser")
    public JAXBElement<DispenserType> createRequestDispenser(DispenserType value) {
        return new JAXBElement<DispenserType>(_RequestDispenser_QNAME, DispenserType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPrescriptionDateRangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "RequestPrescriptionDateRange")
    public JAXBElement<RequestPrescriptionDateRangeType> createRequestPrescriptionDateRange(RequestPrescriptionDateRangeType value) {
        return new JAXBElement<RequestPrescriptionDateRangeType>(_RequestPrescriptionDateRange_QNAME, RequestPrescriptionDateRangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonStateIssuedIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "PersonIdentifier")
    public JAXBElement<IdentificationType> createPersonStateIssuedIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_PersonStateIssuedIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PartialFillIndicator")
    public JAXBElement<Boolean> createPartialFillIndicator(Boolean value) {
        return new JAXBElement<Boolean>(_PartialFillIndicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PatientNameOfAnimalText")
    public JAXBElement<TextType> createPatientNameOfAnimalText(TextType value) {
        return new JAXBElement<TextType>(_PatientNameOfAnimalText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientSequenceNumber")
    public JAXBElement<NonNegativeInteger> createCompoundDrugIngredientSequenceNumber(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_CompoundDrugIngredientSequenceNumber_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PMPDocumentAugmentationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PMPDocumentAugmentation", substitutionHeadNamespace = "http://niem.gov/niem/structures/2.0", substitutionHeadName = "Augmentation")
    public JAXBElement<PMPDocumentAugmentationType> createPMPDocumentAugmentation(PMPDocumentAugmentationType value) {
        return new JAXBElement<PMPDocumentAugmentationType>(_PMPDocumentAugmentation_QNAME, PMPDocumentAugmentationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonOtherIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "PersonIdentifier")
    public JAXBElement<IdentificationType> createPersonOtherIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_PersonOtherIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugDosageUnitsCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDrugDosageUnitsCode(String value) {
        return new JAXBElement<String>(_DrugDosageUnitsCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientDINProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "CompoundDrugIngredientProductIdentifier")
    public JAXBElement<IdentificationType> createCompoundDrugIngredientDINProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_CompoundDrugIngredientDINProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonPickingUpRxType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonPickingUpRx")
    public JAXBElement<PersonPickingUpRxType> createPersonPickingUpRx(PersonPickingUpRxType value) {
        return new JAXBElement<PersonPickingUpRxType>(_PersonPickingUpRx_QNAME, PersonPickingUpRxType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "Prescription")
    public JAXBElement<PrescriptionType> createPrescription(PrescriptionType value) {
        return new JAXBElement<PrescriptionType>(_Prescription_QNAME, PrescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "RefillsAuthorizedCount")
    public JAXBElement<NonNegativeInteger> createRefillsAuthorizedCount(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_RefillsAuthorizedCount_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Decimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "IngredientQuantity")
    public JAXBElement<Decimal> createIngredientQuantity(Decimal value) {
        return new JAXBElement<Decimal>(_IngredientQuantity_QNAME, Decimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PrescriberDEANumberSuffixText")
    public JAXBElement<TextType> createPrescriberDEANumberSuffixText(TextType value) {
        return new JAXBElement<TextType>(_PrescriberDEANumberSuffixText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugRefillNumberCount")
    public JAXBElement<NonNegativeInteger> createDrugRefillNumberCount(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_DrugRefillNumberCount_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PrescriptionFilledDate")
    public JAXBElement<DateType> createPrescriptionFilledDate(DateType value) {
        return new JAXBElement<DateType>(_PrescriptionFilledDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompoundDrugIngredientType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredient")
    public JAXBElement<CompoundDrugIngredientType> createCompoundDrugIngredient(CompoundDrugIngredientType value) {
        return new JAXBElement<CompoundDrugIngredientType>(_CompoundDrugIngredient_QNAME, CompoundDrugIngredientType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "Patient")
    public JAXBElement<PatientType> createPatient(PatientType value) {
        return new JAXBElement<PatientType>(_Patient_QNAME, PatientType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonMilitaryIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "PersonIdentifier")
    public JAXBElement<IdentificationType> createPersonMilitaryIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_PersonMilitaryIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "TransactionTypeCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTransactionTypeCode(String value) {
        return new JAXBElement<String>(_TransactionTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugProductIdentifier")
    public JAXBElement<Object> createDrugProductIdentifier(Object value) {
        return new JAXBElement<Object>(_DrugProductIdentifier_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "InformationSourceEntityNameText")
    public JAXBElement<TextType> createInformationSourceEntityNameText(TextType value) {
        return new JAXBElement<TextType>(_InformationSourceEntityNameText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "ContactNameText")
    public JAXBElement<TextType> createContactNameText(TextType value) {
        return new JAXBElement<TextType>(_ContactNameText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "Document")
    public JAXBElement<DocumentType> createDocument(DocumentType value) {
        return new JAXBElement<DocumentType>(_Document_QNAME, DocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "StateLicenseIdentifier")
    public JAXBElement<IdentificationType> createStateLicenseIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_StateLicenseIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReportDateRangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "ReportDateRange")
    public JAXBElement<ReportDateRangeType> createReportDateRange(ReportDateRangeType value) {
        return new JAXBElement<ReportDateRangeType>(_ReportDateRange_QNAME, ReportDateRangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PharmacistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "Pharmacist")
    public JAXBElement<PharmacistType> createPharmacist(PharmacistType value) {
        return new JAXBElement<PharmacistType>(_Pharmacist_QNAME, PharmacistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrescriptionForReportingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PrescriptionForReporting")
    public JAXBElement<PrescriptionForReportingType> createPrescriptionForReporting(PrescriptionForReportingType value) {
        return new JAXBElement<PrescriptionForReportingType>(_PrescriptionForReporting_QNAME, PrescriptionForReportingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileTypeCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "FileTypeCode")
    public JAXBElement<FileTypeCodeType> createFileTypeCode(FileTypeCodeType value) {
        return new JAXBElement<FileTypeCodeType>(_FileTypeCode_QNAME, FileTypeCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "NCPDPIdentifier")
    public JAXBElement<IdentificationType> createNCPDPIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_NCPDPIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugDINProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "DrugProductIdentifier")
    public JAXBElement<IdentificationType> createDrugDINProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_DrugDINProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugNDCProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "DrugProductIdentifier")
    public JAXBElement<IdentificationType> createDrugNDCProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_DrugNDCProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "RelationshipToPatientCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRelationshipToPatientCode(String value) {
        return new JAXBElement<String>(_RelationshipToPatientCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonPrimaryContactInformation")
    public JAXBElement<ContactInformationType> createPersonPrimaryContactInformation(ContactInformationType value) {
        return new JAXBElement<ContactInformationType>(_PersonPrimaryContactInformation_QNAME, ContactInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrescriberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "Prescriber")
    public JAXBElement<PrescriberType> createPrescriber(PrescriberType value) {
        return new JAXBElement<PrescriberType>(_Prescriber_QNAME, PrescriberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonUniqueSystemIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "PersonIdentifier")
    public JAXBElement<IdentificationType> createPersonUniqueSystemIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_PersonUniqueSystemIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PatientLocationCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPatientLocationCode(String value) {
        return new JAXBElement<String>(_PatientLocationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugCPDProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "DrugProductIdentifier")
    public JAXBElement<IdentificationType> createDrugCPDProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_DrugCPDProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientDEAClassScheduleText")
    public JAXBElement<TextType> createCompoundDrugIngredientDEAClassScheduleText(TextType value) {
        return new JAXBElement<TextType>(_CompoundDrugIngredientDEAClassScheduleText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "ReportDateRangeBegin", substitutionHeadNamespace = "http://niem.gov/niem/niem-core/2.0", substitutionHeadName = "DateRepresentation")
    public JAXBElement<Date> createReportDateRangeBegin(Date value) {
        return new JAXBElement<Date>(_ReportDateRangeBegin_QNAME, Date.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "ReportDateRangeEnd", substitutionHeadNamespace = "http://niem.gov/niem/niem-core/2.0", substitutionHeadName = "DateRepresentation")
    public JAXBElement<Date> createReportDateRangeEnd(Date value) {
        return new JAXBElement<Date>(_ReportDateRangeEnd_QNAME, Date.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestResponsePrescriptionReportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "RequestResponsePrescriptionReport", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "PrescriptionReport")
    public JAXBElement<RequestResponsePrescriptionReportType> createRequestResponsePrescriptionReport(RequestResponsePrescriptionReportType value) {
        return new JAXBElement<RequestResponsePrescriptionReportType>(_RequestResponsePrescriptionReport_QNAME, RequestResponsePrescriptionReportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "VersionReleaseNumberText")
    public JAXBElement<TextType> createVersionReleaseNumberText(TextType value) {
        return new JAXBElement<TextType>(_VersionReleaseNumberText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "RoutingNumber")
    public JAXBElement<NonNegativeInteger> createRoutingNumber(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_RoutingNumber_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Decimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DispensedQuantity")
    public JAXBElement<Decimal> createDispensedQuantity(Decimal value) {
        return new JAXBElement<Decimal>(_DispensedQuantity_QNAME, Decimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "ResponseIDText")
    public JAXBElement<TextType> createResponseIDText(TextType value) {
        return new JAXBElement<TextType>(_ResponseIDText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "NPIIdentifier")
    public JAXBElement<IdentificationType> createNPIIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_NPIIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DEAClassScheduleText")
    public JAXBElement<TextType> createDEAClassScheduleText(TextType value) {
        return new JAXBElement<TextType>(_DEAClassScheduleText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "ReportingStatusCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReportingStatusCode(String value) {
        return new JAXBElement<String>(_ReportingStatusCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "RequestPrescriptionDateRangeEnd", substitutionHeadNamespace = "http://niem.gov/niem/niem-core/2.0", substitutionHeadName = "DateRepresentation")
    public JAXBElement<Date> createRequestPrescriptionDateRangeEnd(Date value) {
        return new JAXBElement<Date>(_RequestPrescriptionDateRangeEnd_QNAME, Date.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonTribalIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "PersonIdentifier")
    public JAXBElement<IdentificationType> createPersonTribalIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_PersonTribalIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugHRIProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "DrugProductIdentifier")
    public JAXBElement<IdentificationType> createDrugHRIProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_DrugHRIProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DEANumberIdentifier")
    public JAXBElement<IdentificationType> createDEANumberIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_DEANumberIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientNDCProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "CompoundDrugIngredientProductIdentifier")
    public JAXBElement<IdentificationType> createCompoundDrugIngredientNDCProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_CompoundDrugIngredientNDCProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "CompoundDrugIngredientUPCProductIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "CompoundDrugIngredientProductIdentifier")
    public JAXBElement<IdentificationType> createCompoundDrugIngredientUPCProductIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_CompoundDrugIngredientUPCProductIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "ChainSiteIDText")
    public JAXBElement<TextType> createChainSiteIDText(TextType value) {
        return new JAXBElement<TextType>(_ChainSiteIDText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PrescriptionReport")
    public JAXBElement<Object> createPrescriptionReport(Object value) {
        return new JAXBElement<Object>(_PrescriptionReport_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonPassportIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "PersonIdentifier")
    public JAXBElement<IdentificationType> createPersonPassportIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_PersonPassportIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Time }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "ReportExecutionTime")
    public JAXBElement<Time> createReportExecutionTime(Time value) {
        return new JAXBElement<Time>(_ReportExecutionTime_QNAME, Time.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PrescriptionNormCodeText")
    public JAXBElement<TextType> createPrescriptionNormCodeText(TextType value) {
        return new JAXBElement<TextType>(_PrescriptionNormCodeText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "Organization")
    public JAXBElement<OrganizationType> createOrganization(OrganizationType value) {
        return new JAXBElement<OrganizationType>(_Organization_QNAME, OrganizationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "StateIssuedRxSerialNumberIdentifier")
    public JAXBElement<IdentificationType> createStateIssuedRxSerialNumberIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_StateIssuedRxSerialNumberIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "TransactionControlNumberText")
    public JAXBElement<TextType> createTransactionControlNumberText(TextType value) {
        return new JAXBElement<TextType>(_TransactionControlNumberText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "DrugUnitOfMeasureText")
    public JAXBElement<TextType> createDrugUnitOfMeasureText(TextType value) {
        return new JAXBElement<TextType>(_DrugUnitOfMeasureText_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrescriberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "RequestPrescriber")
    public JAXBElement<PrescriberType> createRequestPrescriber(PrescriberType value) {
        return new JAXBElement<PrescriberType>(_RequestPrescriber_QNAME, PrescriberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "PersonDriverLicenseIdentifier", substitutionHeadNamespace = "http://xml.ijis.org/niem/2.0/extension", substitutionHeadName = "PersonIdentifier")
    public JAXBElement<IdentificationType> createPersonDriverLicenseIdentifier(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_PersonDriverLicenseIdentifier_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ijis.org/niem/2.0/extension", name = "UniqueInformationSourceIDText")
    public JAXBElement<TextType> createUniqueInformationSourceIDText(TextType value) {
        return new JAXBElement<TextType>(_UniqueInformationSourceIDText_QNAME, TextType.class, null, value);
    }

}
