//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.niem._2_0.extension;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import gov.niem.niem.niem_core._2.TextType;
import gov.niem.niem.proxy.xsd._2.Date;
import gov.niem.niem.proxy.xsd._2.NonNegativeInteger;
import gov.niem.niem.proxy.xsd._2.Time;
import org.ijis.xml.pmpcode.FileTypeCodeType;


/**
 * <p>Java class for PharmacyReportingPrescriptionReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PharmacyReportingPrescriptionReportType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xml.ijis.org/niem/2.0/extension}DocumentType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}VersionReleaseNumberText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}TransactionControlNumberText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}TransactionTypeCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ResponseIDText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ReportExecutionDate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ReportExecutionTime" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}FileTypeCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}RoutingNumber" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}UniqueInformationSourceIDText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}InformationSourceEntityNameText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}MessageText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}PrescriptionForReporting" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PharmacyReportingPrescriptionReportType", propOrder = {
    "versionReleaseNumberText",
    "transactionControlNumberText",
    "transactionTypeCode",
    "responseIDText",
    "reportExecutionDate",
    "reportExecutionTime",
    "fileTypeCode",
    "routingNumber",
    "uniqueInformationSourceIDText",
    "informationSourceEntityNameText",
    "messageText",
    "prescriptionForReporting"
})
public class PharmacyReportingPrescriptionReportType
    extends DocumentType
{

    @XmlElement(name = "VersionReleaseNumberText", nillable = true)
    protected List<TextType> versionReleaseNumberText;
    @XmlElement(name = "TransactionControlNumberText", nillable = true)
    protected List<TextType> transactionControlNumberText;
    @XmlElement(name = "TransactionTypeCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected List<String> transactionTypeCode;
    @XmlElement(name = "ResponseIDText", nillable = true)
    protected List<TextType> responseIDText;
    @XmlElement(name = "ReportExecutionDate", nillable = true)
    protected List<Date> reportExecutionDate;
    @XmlElement(name = "ReportExecutionTime", nillable = true)
    protected List<Time> reportExecutionTime;
    @XmlElement(name = "FileTypeCode")
    protected List<FileTypeCodeType> fileTypeCode;
    @XmlElement(name = "RoutingNumber", nillable = true)
    protected List<NonNegativeInteger> routingNumber;
    @XmlElement(name = "UniqueInformationSourceIDText", nillable = true)
    protected List<TextType> uniqueInformationSourceIDText;
    @XmlElement(name = "InformationSourceEntityNameText", nillable = true)
    protected List<TextType> informationSourceEntityNameText;
    @XmlElement(name = "MessageText", nillable = true)
    protected List<TextType> messageText;
    @XmlElement(name = "PrescriptionForReporting", nillable = true)
    protected List<PrescriptionForReportingType> prescriptionForReporting;

    /**
     * Gets the value of the versionReleaseNumberText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the versionReleaseNumberText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVersionReleaseNumberText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getVersionReleaseNumberText() {
        if (versionReleaseNumberText == null) {
            versionReleaseNumberText = new ArrayList<TextType>();
        }
        return this.versionReleaseNumberText;
    }

    /**
     * Gets the value of the transactionControlNumberText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transactionControlNumberText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransactionControlNumberText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getTransactionControlNumberText() {
        if (transactionControlNumberText == null) {
            transactionControlNumberText = new ArrayList<TextType>();
        }
        return this.transactionControlNumberText;
    }

    /**
     * Gets the value of the transactionTypeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transactionTypeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransactionTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTransactionTypeCode() {
        if (transactionTypeCode == null) {
            transactionTypeCode = new ArrayList<String>();
        }
        return this.transactionTypeCode;
    }

    /**
     * Gets the value of the responseIDText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responseIDText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponseIDText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getResponseIDText() {
        if (responseIDText == null) {
            responseIDText = new ArrayList<TextType>();
        }
        return this.responseIDText;
    }

    /**
     * Gets the value of the reportExecutionDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportExecutionDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportExecutionDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Date }
     * 
     * 
     */
    public List<Date> getReportExecutionDate() {
        if (reportExecutionDate == null) {
            reportExecutionDate = new ArrayList<Date>();
        }
        return this.reportExecutionDate;
    }

    /**
     * Gets the value of the reportExecutionTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportExecutionTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportExecutionTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Time }
     * 
     * 
     */
    public List<Time> getReportExecutionTime() {
        if (reportExecutionTime == null) {
            reportExecutionTime = new ArrayList<Time>();
        }
        return this.reportExecutionTime;
    }

    /**
     * Gets the value of the fileTypeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileTypeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileTypeCodeType }
     * 
     * 
     */
    public List<FileTypeCodeType> getFileTypeCode() {
        if (fileTypeCode == null) {
            fileTypeCode = new ArrayList<FileTypeCodeType>();
        }
        return this.fileTypeCode;
    }

    /**
     * Gets the value of the routingNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routingNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoutingNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonNegativeInteger }
     * 
     * 
     */
    public List<NonNegativeInteger> getRoutingNumber() {
        if (routingNumber == null) {
            routingNumber = new ArrayList<NonNegativeInteger>();
        }
        return this.routingNumber;
    }

    /**
     * Gets the value of the uniqueInformationSourceIDText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uniqueInformationSourceIDText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUniqueInformationSourceIDText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getUniqueInformationSourceIDText() {
        if (uniqueInformationSourceIDText == null) {
            uniqueInformationSourceIDText = new ArrayList<TextType>();
        }
        return this.uniqueInformationSourceIDText;
    }

    /**
     * Gets the value of the informationSourceEntityNameText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the informationSourceEntityNameText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInformationSourceEntityNameText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getInformationSourceEntityNameText() {
        if (informationSourceEntityNameText == null) {
            informationSourceEntityNameText = new ArrayList<TextType>();
        }
        return this.informationSourceEntityNameText;
    }

    /**
     * Gets the value of the messageText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getMessageText() {
        if (messageText == null) {
            messageText = new ArrayList<TextType>();
        }
        return this.messageText;
    }

    /**
     * Gets the value of the prescriptionForReporting property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriptionForReporting property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriptionForReporting().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrescriptionForReportingType }
     * 
     * 
     */
    public List<PrescriptionForReportingType> getPrescriptionForReporting() {
        if (prescriptionForReporting == null) {
            prescriptionForReporting = new ArrayList<PrescriptionForReportingType>();
        }
        return this.prescriptionForReporting;
    }

}
