/*
   Copyright 2013 Collaborative For Universal Health (C4UH), Logicoy Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
  */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.niem._2_0.extension;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import gov.niem.niem.niem_core._2.TextType;
import gov.niem.niem.proxy.xsd._2.Date;


/**
 * <p>Java class for PrescriptionForReportingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrescriptionForReportingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xml.ijis.org/niem/2.0/extension}PrescriptionType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ReportingStatusCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}PrescriptionSoldDate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}PrescriptionNormCodeText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}PrescriptionElectronicReferenceNumberText" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrescriptionForReportingType", propOrder = {
    "reportingStatusCode",
    "prescriptionSoldDate",
    "prescriptionNormCodeText",
    "prescriptionElectronicReferenceNumberText"
})
public class PrescriptionForReportingType
    extends PrescriptionType
{

    @XmlElement(name = "ReportingStatusCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected List<String> reportingStatusCode;
    @XmlElement(name = "PrescriptionSoldDate", nillable = true)
    protected List<Date> prescriptionSoldDate;
    @XmlElement(name = "PrescriptionNormCodeText", nillable = true)
    protected List<TextType> prescriptionNormCodeText;
    @XmlElement(name = "PrescriptionElectronicReferenceNumberText", nillable = true)
    protected List<TextType> prescriptionElectronicReferenceNumberText;

    /**
     * Gets the value of the reportingStatusCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportingStatusCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportingStatusCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getReportingStatusCode() {
        if (reportingStatusCode == null) {
            reportingStatusCode = new ArrayList<String>();
        }
        return this.reportingStatusCode;
    }

    /**
     * Gets the value of the prescriptionSoldDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriptionSoldDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriptionSoldDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Date }
     * 
     * 
     */
    public List<Date> getPrescriptionSoldDate() {
        if (prescriptionSoldDate == null) {
            prescriptionSoldDate = new ArrayList<Date>();
        }
        return this.prescriptionSoldDate;
    }

    /**
     * Gets the value of the prescriptionNormCodeText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriptionNormCodeText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriptionNormCodeText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getPrescriptionNormCodeText() {
        if (prescriptionNormCodeText == null) {
            prescriptionNormCodeText = new ArrayList<TextType>();
        }
        return this.prescriptionNormCodeText;
    }

    /**
     * Gets the value of the prescriptionElectronicReferenceNumberText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriptionElectronicReferenceNumberText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriptionElectronicReferenceNumberText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getPrescriptionElectronicReferenceNumberText() {
        if (prescriptionElectronicReferenceNumberText == null) {
            prescriptionElectronicReferenceNumberText = new ArrayList<TextType>();
        }
        return this.prescriptionElectronicReferenceNumberText;
    }

}
