/*
   Copyright 2013 Collaborative For Universal Health (C4UH), Logicoy Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
  */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.niem._2_0.extension;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import gov.niem.niem.niem_core._2.DateType;
import gov.niem.niem.niem_core._2.IdentificationType;
import gov.niem.niem.niem_core._2.TextType;
import gov.niem.niem.proxy.xsd._2.Boolean;
import gov.niem.niem.proxy.xsd._2.Decimal;
import gov.niem.niem.proxy.xsd._2.NonNegativeInteger;
import gov.niem.niem.structures._2.ComplexObjectType;


/**
 * Information from a completed prescription form and additional information add through PMP analysis.
 * 			
 * 
 * <p>Java class for PrescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrescriptionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://niem.gov/niem/structures/2.0}ComplexObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}Dispenser" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}PrescriptionNumberText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}DrugRefillNumberCount" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}PrescriptionFilledDate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}Patient" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}Prescriber" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}PrescriptionWrittenDate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}PrescriptionDrug" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}RefillsAuthorizedCount" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}DispensedQuantity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}DaysSupplyCount" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}DrugDosageUnitsCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}MethodOfPaymentCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}TransmissionFormOfRxOriginCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}PartialFillIndicator" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}Pharmacist" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}StateIssuedRxSerialNumberIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrescriptionType", propOrder = {
    "dispenser",
    "prescriptionNumberText",
    "drugRefillNumberCount",
    "prescriptionFilledDate",
    "patient",
    "prescriber",
    "prescriptionWrittenDate",
    "prescriptionDrug",
    "refillsAuthorizedCount",
    "dispensedQuantity",
    "daysSupplyCount",
    "drugDosageUnitsCode",
    "methodOfPaymentCode",
    "transmissionFormOfRxOriginCode",
    "partialFillIndicator",
    "pharmacist",
    "stateIssuedRxSerialNumberIdentifier"
})
@XmlSeeAlso({
    PrescriptionForReportingType.class
})
public class PrescriptionType
    extends ComplexObjectType
{

    @XmlElement(name = "Dispenser", nillable = true)
    protected List<DispenserType> dispenser;
    @XmlElement(name = "PrescriptionNumberText", nillable = true)
    protected List<TextType> prescriptionNumberText;
    @XmlElement(name = "DrugRefillNumberCount", nillable = true)
    protected List<NonNegativeInteger> drugRefillNumberCount;
    @XmlElement(name = "PrescriptionFilledDate", nillable = true)
    protected List<DateType> prescriptionFilledDate;
    @XmlElement(name = "Patient")
    protected List<PatientType> patient;
    @XmlElement(name = "Prescriber", nillable = true)
    protected List<PrescriberType> prescriber;
    @XmlElement(name = "PrescriptionWrittenDate", nillable = true)
    protected List<DateType> prescriptionWrittenDate;
    @XmlElement(name = "PrescriptionDrug", nillable = true)
    protected List<PrescriptionDrugType> prescriptionDrug;
    @XmlElement(name = "RefillsAuthorizedCount", nillable = true)
    protected List<NonNegativeInteger> refillsAuthorizedCount;
    @XmlElement(name = "DispensedQuantity", nillable = true)
    protected List<Decimal> dispensedQuantity;
    @XmlElement(name = "DaysSupplyCount", nillable = true)
    protected List<NonNegativeInteger> daysSupplyCount;
    @XmlElement(name = "DrugDosageUnitsCode", nillable = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected List<String> drugDosageUnitsCode;
    @XmlElement(name = "MethodOfPaymentCode", nillable = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected List<String> methodOfPaymentCode;
    @XmlElement(name = "TransmissionFormOfRxOriginCode", nillable = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected List<String> transmissionFormOfRxOriginCode;
    @XmlElement(name = "PartialFillIndicator", nillable = true)
    protected List<Boolean> partialFillIndicator;
    @XmlElement(name = "Pharmacist", nillable = true)
    protected List<PharmacistType> pharmacist;
    @XmlElement(name = "StateIssuedRxSerialNumberIdentifier", nillable = true)
    protected List<IdentificationType> stateIssuedRxSerialNumberIdentifier;

    /**
     * Gets the value of the dispenser property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dispenser property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDispenser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DispenserType }
     * 
     * 
     */
    public List<DispenserType> getDispenser() {
        if (dispenser == null) {
            dispenser = new ArrayList<DispenserType>();
        }
        return this.dispenser;
    }

    /**
     * Gets the value of the prescriptionNumberText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriptionNumberText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriptionNumberText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getPrescriptionNumberText() {
        if (prescriptionNumberText == null) {
            prescriptionNumberText = new ArrayList<TextType>();
        }
        return this.prescriptionNumberText;
    }

    /**
     * Gets the value of the drugRefillNumberCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drugRefillNumberCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrugRefillNumberCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonNegativeInteger }
     * 
     * 
     */
    public List<NonNegativeInteger> getDrugRefillNumberCount() {
        if (drugRefillNumberCount == null) {
            drugRefillNumberCount = new ArrayList<NonNegativeInteger>();
        }
        return this.drugRefillNumberCount;
    }

    /**
     * Gets the value of the prescriptionFilledDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriptionFilledDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriptionFilledDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getPrescriptionFilledDate() {
        if (prescriptionFilledDate == null) {
            prescriptionFilledDate = new ArrayList<DateType>();
        }
        return this.prescriptionFilledDate;
    }

    /**
     * Gets the value of the patient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatientType }
     * 
     * 
     */
    public List<PatientType> getPatient() {
        if (patient == null) {
            patient = new ArrayList<PatientType>();
        }
        return this.patient;
    }

    /**
     * Gets the value of the prescriber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrescriberType }
     * 
     * 
     */
    public List<PrescriberType> getPrescriber() {
        if (prescriber == null) {
            prescriber = new ArrayList<PrescriberType>();
        }
        return this.prescriber;
    }

    /**
     * Gets the value of the prescriptionWrittenDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriptionWrittenDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriptionWrittenDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getPrescriptionWrittenDate() {
        if (prescriptionWrittenDate == null) {
            prescriptionWrittenDate = new ArrayList<DateType>();
        }
        return this.prescriptionWrittenDate;
    }

    /**
     * Gets the value of the prescriptionDrug property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriptionDrug property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriptionDrug().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrescriptionDrugType }
     * 
     * 
     */
    public List<PrescriptionDrugType> getPrescriptionDrug() {
        if (prescriptionDrug == null) {
            prescriptionDrug = new ArrayList<PrescriptionDrugType>();
        }
        return this.prescriptionDrug;
    }

    /**
     * Gets the value of the refillsAuthorizedCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refillsAuthorizedCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefillsAuthorizedCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonNegativeInteger }
     * 
     * 
     */
    public List<NonNegativeInteger> getRefillsAuthorizedCount() {
        if (refillsAuthorizedCount == null) {
            refillsAuthorizedCount = new ArrayList<NonNegativeInteger>();
        }
        return this.refillsAuthorizedCount;
    }

    /**
     * Gets the value of the dispensedQuantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dispensedQuantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDispensedQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Decimal }
     * 
     * 
     */
    public List<Decimal> getDispensedQuantity() {
        if (dispensedQuantity == null) {
            dispensedQuantity = new ArrayList<Decimal>();
        }
        return this.dispensedQuantity;
    }

    /**
     * Gets the value of the daysSupplyCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the daysSupplyCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDaysSupplyCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonNegativeInteger }
     * 
     * 
     */
    public List<NonNegativeInteger> getDaysSupplyCount() {
        if (daysSupplyCount == null) {
            daysSupplyCount = new ArrayList<NonNegativeInteger>();
        }
        return this.daysSupplyCount;
    }

    /**
     * Gets the value of the drugDosageUnitsCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drugDosageUnitsCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrugDosageUnitsCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDrugDosageUnitsCode() {
        if (drugDosageUnitsCode == null) {
            drugDosageUnitsCode = new ArrayList<String>();
        }
        return this.drugDosageUnitsCode;
    }

    /**
     * Gets the value of the methodOfPaymentCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the methodOfPaymentCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMethodOfPaymentCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMethodOfPaymentCode() {
        if (methodOfPaymentCode == null) {
            methodOfPaymentCode = new ArrayList<String>();
        }
        return this.methodOfPaymentCode;
    }

    /**
     * Gets the value of the transmissionFormOfRxOriginCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transmissionFormOfRxOriginCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransmissionFormOfRxOriginCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTransmissionFormOfRxOriginCode() {
        if (transmissionFormOfRxOriginCode == null) {
            transmissionFormOfRxOriginCode = new ArrayList<String>();
        }
        return this.transmissionFormOfRxOriginCode;
    }

    /**
     * Gets the value of the partialFillIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partialFillIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartialFillIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getPartialFillIndicator() {
        if (partialFillIndicator == null) {
            partialFillIndicator = new ArrayList<Boolean>();
        }
        return this.partialFillIndicator;
    }

    /**
     * Gets the value of the pharmacist property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pharmacist property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPharmacist().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PharmacistType }
     * 
     * 
     */
    public List<PharmacistType> getPharmacist() {
        if (pharmacist == null) {
            pharmacist = new ArrayList<PharmacistType>();
        }
        return this.pharmacist;
    }

    /**
     * Gets the value of the stateIssuedRxSerialNumberIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stateIssuedRxSerialNumberIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStateIssuedRxSerialNumberIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getStateIssuedRxSerialNumberIdentifier() {
        if (stateIssuedRxSerialNumberIdentifier == null) {
            stateIssuedRxSerialNumberIdentifier = new ArrayList<IdentificationType>();
        }
        return this.stateIssuedRxSerialNumberIdentifier;
    }

}
