//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.niem._2_0.extension;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.niem.proxy.xsd._2.Date;
import gov.niem.niem.structures._2.ComplexObjectType;


/**
 * 
 *         Date range for prescription dispensing being reported
 *       
 * 
 * <p>Java class for ReportDateRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportDateRangeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://niem.gov/niem/structures/2.0}ComplexObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ReportDateRangeBegin"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ReportDateRangeEnd"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportDateRangeType", propOrder = {
    "reportDateRangeBegin",
    "reportDateRangeEnd"
})
public class ReportDateRangeType
    extends ComplexObjectType
{

    @XmlElement(name = "ReportDateRangeBegin", required = true, nillable = true)
    protected Date reportDateRangeBegin;
    @XmlElement(name = "ReportDateRangeEnd", required = true, nillable = true)
    protected Date reportDateRangeEnd;

    /**
     * Gets the value of the reportDateRangeBegin property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getReportDateRangeBegin() {
        return reportDateRangeBegin;
    }

    /**
     * Sets the value of the reportDateRangeBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setReportDateRangeBegin(Date value) {
        this.reportDateRangeBegin = value;
    }

    /**
     * Gets the value of the reportDateRangeEnd property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getReportDateRangeEnd() {
        return reportDateRangeEnd;
    }

    /**
     * Sets the value of the reportDateRangeEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setReportDateRangeEnd(Date value) {
        this.reportDateRangeEnd = value;
    }

}
