//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.niem._2_0.extension;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.niem.proxy.xsd._2.Date;
import gov.niem.niem.proxy.xsd._2.Time;


/**
 * Report listing prescription activity sent in response to the request.
 * 			
 * 
 * <p>Java class for RequestResponsePrescriptionReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestResponsePrescriptionReportType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xml.ijis.org/niem/2.0/extension}DocumentType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ReportExecutionDate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ReportExecutionTime" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}ReportDateRange" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xml.ijis.org/niem/2.0/extension}Prescription" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestResponsePrescriptionReportType", propOrder = {
    "reportExecutionDate",
    "reportExecutionTime",
    "reportDateRange",
    "prescription"
})
public class RequestResponsePrescriptionReportType
    extends DocumentType
{

    @XmlElement(name = "ReportExecutionDate", nillable = true)
    protected List<Date> reportExecutionDate;
    @XmlElement(name = "ReportExecutionTime", nillable = true)
    protected List<Time> reportExecutionTime;
    @XmlElement(name = "ReportDateRange", nillable = true)
    protected List<ReportDateRangeType> reportDateRange;
    @XmlElement(name = "Prescription", nillable = true)
    protected List<PrescriptionType> prescription;

    /**
     * Gets the value of the reportExecutionDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportExecutionDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportExecutionDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Date }
     * 
     * 
     */
    public List<Date> getReportExecutionDate() {
        if (reportExecutionDate == null) {
            reportExecutionDate = new ArrayList<Date>();
        }
        return this.reportExecutionDate;
    }

    /**
     * Gets the value of the reportExecutionTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportExecutionTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportExecutionTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Time }
     * 
     * 
     */
    public List<Time> getReportExecutionTime() {
        if (reportExecutionTime == null) {
            reportExecutionTime = new ArrayList<Time>();
        }
        return this.reportExecutionTime;
    }

    /**
     * Gets the value of the reportDateRange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportDateRange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportDateRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportDateRangeType }
     * 
     * 
     */
    public List<ReportDateRangeType> getReportDateRange() {
        if (reportDateRange == null) {
            reportDateRange = new ArrayList<ReportDateRangeType>();
        }
        return this.reportDateRange;
    }

    /**
     * Gets the value of the prescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrescriptionType }
     * 
     * 
     */
    public List<PrescriptionType> getPrescription() {
        if (prescription == null) {
            prescription = new ArrayList<PrescriptionType>();
        }
        return this.prescription;
    }

}
