/*
   Copyright 2013 Collaborative For Universal Health (C4UH), Logicoy Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
  */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.pmpcode;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExchangeActivityGroupingCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExchangeActivityGroupingCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="RV"/>
 *     &lt;enumeration value="RA"/>
 *     &lt;enumeration value="RC"/>
 *     &lt;enumeration value="RS"/>
 *     &lt;enumeration value="RR"/>
 *     &lt;enumeration value="RP"/>
 *     &lt;enumeration value="SR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExchangeActivityGroupingCodeSimpleType")
@XmlEnum
public enum ExchangeActivityGroupingCodeSimpleType {


    /**
     * Request Valid  
     * 
     */
    RV,

    /**
     * Request Approved  
     * 
     */
    RA,

    /**
     * Request Response Completed  
     * 
     */
    RC,

    /**
     * Request Sent  
     * 
     */
    RS,

    /**
     * Request Response Received  
     * 
     */
    RR,

    /**
     * Request Response Processed
     * 
     */
    RP,

    /**
     * Request Response Sent
     * 
     */
    SR;

    public String value() {
        return name();
    }

    public static ExchangeActivityGroupingCodeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
