//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.pmpcode;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ijis.xml.pmpcode package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ijis.xml.pmpcode
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReportStatusCodeType }
     * 
     */
    public ReportStatusCodeType createReportStatusCodeType() {
        return new ReportStatusCodeType();
    }

    /**
     * Create an instance of {@link ParticipantRoleCodeType }
     * 
     */
    public ParticipantRoleCodeType createParticipantRoleCodeType() {
        return new ParticipantRoleCodeType();
    }

    /**
     * Create an instance of {@link ExchangeActivityGroupingCodeType }
     * 
     */
    public ExchangeActivityGroupingCodeType createExchangeActivityGroupingCodeType() {
        return new ExchangeActivityGroupingCodeType();
    }

}
