//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.04 at 02:02:33 PM IST 
//


package org.ijis.xml.pmpcode;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParticipantRoleCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParticipantRoleCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Prescriber"/>
 *     &lt;enumeration value="Pharmacist"/>
 *     &lt;enumeration value="Law Enforcement"/>
 *     &lt;enumeration value="Regulator"/>
 *     &lt;enumeration value="Researcher"/>
 *     &lt;enumeration value="Patient"/>
 *     &lt;enumeration value="Medicaid"/>
 *     &lt;enumeration value="Judge"/>
 *     &lt;enumeration value="Examiner"/>
 *     &lt;enumeration value="Practitioner"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ParticipantRoleCodeSimpleType")
@XmlEnum
public enum ParticipantRoleCodeSimpleType {


    /**
     * Individual who issued the prescription for specific drugs
     * 
     */
    @XmlEnumValue("Prescriber")
    PRESCRIBER("Prescriber"),

    /**
     * licensed individual who is responsible for filling the prescription.
     * 
     */
    @XmlEnumValue("Pharmacist")
    PHARMACIST("Pharmacist"),

    /**
     * Need Definition 1
     * 
     */
    @XmlEnumValue("Law Enforcement")
    LAW_ENFORCEMENT("Law Enforcement"),

    /**
     * Need Definition 2
     * 
     */
    @XmlEnumValue("Regulator")
    REGULATOR("Regulator"),

    /**
     * Need Definition 3
     * 
     */
    @XmlEnumValue("Researcher")
    RESEARCHER("Researcher"),

    /**
     * An individual who is under the care of a medical service provider and who is the recipient of a medication
     * 
     */
    @XmlEnumValue("Patient")
    PATIENT("Patient"),

    /**
     * Medicaid  staff and fraud unit staff 
     * 
     */
    @XmlEnumValue("Medicaid")
    MEDICAID("Medicaid"),

    /**
     * Judges administering drug diversion or probation programs
     * 
     */
    @XmlEnumValue("Judge")
    JUDGE("Judge"),

    /**
     * Medical examiner
     * 
     */
    @XmlEnumValue("Examiner")
    EXAMINER("Examiner"),

    /**
     * Health care practitioner intervention programs
     * 
     */
    @XmlEnumValue("Practitioner")
    PRACTITIONER("Practitioner");
    private final String value;

    ParticipantRoleCodeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParticipantRoleCodeSimpleType fromValue(String v) {
        for (ParticipantRoleCodeSimpleType c: ParticipantRoleCodeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
